language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5

cache: bundler

before_install:
  - gem update --system --no-document
  - gem install rake
  - gem install bundler

script: bundle exec rake

deploy:
  provider: rubygems
  api_key:
    secure: pReiutaKz4gErUDrBoLt/a4oMC+KjXBgsUW6uVhdlsvBQ1IYiUjWoV09dBrxlsCsE9Pp0f5vwShKXIe5rUY1AGwXTWxyObNNBffRIz2YrolOJieG8vwEJ7v8sy2GGaxT/mVa1KK0HvNHXI/rpGA+Z3Qg5HqKpvDjrB36CKZgzU9CWrK1+wncuoatHDj5ZDsseXCWaEmQxQjHsYML4Wh2mhfjlthMXuMxAegDb9iY2VydnNZuQUd8An2NJF6BGFOKQySwM2gtrpNO6rhjlMBhIVdZkFx4g2lFJGuyykon0HOrj1jBtJtoHrUWLcu959pfZcqLDO1ut0ZVOXjaxouNu8Hf9+qCXzKwfAAmevkCD3u8LYg0W3MFkBadseyxCUYgInFxBib8Qw4JaVPrF0ccoaOBZYsY77MB+KEx830F/Ag2JLjVJ0CugJ9idzah/vjZLcyNkSi9QBcYeQzbtAU3jMsC0P4yrRYbx4z1eAWHLOPHjr87L8GZY12DXzbjV/Sp9EjpEq4DGBVQRLPkEjvdJiju6e3JzMHAb3CkDtduhdAmYTdUr8qWNSE2da4Hu3+8fRGQVkGdFkJM/WCOuEKBlC041KGGVO4KSJfMBfl4ZX2SmZoc0KC3qNPKK/l2UmF+b5PPXqIpGa0tsCmrXHfevmpJPgwMnvSWdOztxeBlNoU=
  gem: chemex
  on:
    tags: true
    repo: procore/chemex

notifications:
  email: false
